canary and admit1: treat single argument as eval

diff --git a/bin/canary b/bin/canary
--- a/bin/canary
+++ b/bin/canary
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # Usage: canary COMMAND [ARGUMENTS...]
-# Usage: canary SHELL_EXPRESSION...
+# Usage: canary SHELL_EVAL_EXPRESSION
 #
 # Silences (both stdout and stderr) the given command only if it succeeds
 # (exits with status 0) and then propagates its exit status to the caller.
@@ -12,12 +12,21 @@
 #--
 # Written in 2014 by Suraj N. Kurapati
 
-output=$( exec 2>&1 ; set -x ; "$@" )
+output=$(
+  # capture stderr alongside stdout
+  exec 2>&1
+
+  # SHELL_EVAL_EXPRESSION was given
+  test $# -eq 1 && set -- eval "$@"
+
+  # execute the given command line
+  "$@"
+)
 status=$?
 
-if [ $status -ne 0 ]
-then echo "canary: command exited with nonzero exit status: $status" >&2
-     echo "$output" # propagate the output of the command to the user
+if [ $status -ne 0 ]; then
+  echo "canary: command exited with nonzero exit status: $status" >&2
+  echo "$output" # propagate output of failed command back to caller
 fi
 
 exit $status
